# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    tags:
      - 'v*'
  # pull_request:
  #   branches: [ main ]

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: false

  build:
    name: Build Release
    needs: create_release
    strategy:
      matrix:
        os: [macos-latest, ]
        include:
          - os: macos-latest
            release_suffix: mac.tar.xz
          # - os: windows-latest
          #   release_suffix: windows.tar.gz
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -U wheel pip setuptools
          pip install -r requirements.txt
          pip install -U "pyinstaller<5.14,>=5.5"

      - name: Build executable
        run: pyinstaller --clean metabow_bridge.spec --noconfirm

      - name: Mac archive and compress
        if: matrix.os == 'macos-latest'
        run: tar -cJf metabow_bridge_${{ matrix.release_suffix }} -C ${{ runner.workspace }}/sensor-tile-osc/dist/ bridge.app

      # - name: Windows archive and compress
      #   if: matrix.os == 'windows-latest'
      #   run: tar -czf metabow_bridge_${{ matrix.release_suffix }} -C ${{ runner.workspace }}/sensor-tile-osc/dist/ .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: metabow_bridge_${{ matrix.release_suffix }}
