# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bleak python-osc pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile steval_bridge.py
    - name: Tar files
      run: tar -cvzf steval_bridge.tar.gz -C /Users/runner/work/sensor-tile-osc/sensor-tile-osc/dist/steval_bridge .
    - uses: actions/upload-artifact@v2
      with:
        name: steval_bridge
        path: steval_bridge.tar
