# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-10.15, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -U pip setuptools wheel
        pip install bleak python-osc pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller -F metabow_bridge.py
    - name: Archive and compress files
      run: tar -czvf metabow_bridge_${{ matrix.os }}.tar.gz -C ${{ runner.workspace }}/sensor-tile-osc/dist/ .
    # - uses: actions/upload-artifact@v2
      # with:
        # name: metabow_bridge_${{ matrix.os }}
        # path: metabow_bridge_${{ matrix.os }}.tar.gz
    - uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        file: "*.tar.gz"
        tags: false
        verbose: true