# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-11, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install bleak python-osc pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile metabow_bridge.py
    - name: Show workspace
      run: |
        echo ${{runner.workspace}}
    - name: Tar files
      run: tar -cvzf metabow_bridge.tar.gz -C ${{runner.workspace}}/sensor-tile-osc/dist/ .
    - uses: actions/upload-artifact@v2
      with:
        name: metabow_bridge ${{ matrix.os }}
        path: metabow_bridge.tar.gz
